const express = require('express');

// const logger = require('../services/logger');

const asyncHandler = require('../middleware/asyncHandler');
const { accessControl } = require('../middleware/auth');
const openaiService = require('../services/openai');
const { validate } = require('../services/cohorts/phenotype/model');
const logger = require('../services/logger');

const isPermittedTo = accessControl('genai');
const router = express.Router();

router.post(
  '/generate/name-description',
  isPermittedTo('create'),
  asyncHandler(async (req, res) => {
    // #swagger.tags = ['GenAI']
    const metadata = await openaiService.generate_cohort_name_description(req.body.filters);
    res.json(metadata);
  }),
);

router.post(
  '/generate/cohort',
  isPermittedTo('create'),
  asyncHandler(async (req, res) => {
    // #swagger.tags = ['GenAI']
    const json = await openaiService.generate_cohort(req.body.text);
    // console.log(JSON.stringify(json, null, 2));
    const query = {
      schema: {
        name: 'phenotype',
        namespace: 'edu.iu.sca.biobank',
        version: '1.0.0',
      },
      body: {
        filters: json,
        snapshot_id: 1, // todo: get from request
      },
    };
    try {
      validate(query.body); // throws error if invalid
    } catch (e) {
      logger.error('Invalid cohort generated by GenAI:', e);
      logger.error('Generated cohort:', JSON.stringify(query, null, 2));
      throw e;
    }
    res.json({ query });
  }),
);

module.exports = router;
