const swaggerAutogen = require('swagger-autogen')();
const config = require('config');

const doc = {
  info: {
    title: 'API',
    description: 'Auto generated by the <b>swagger-autogen</b> module.',
    contact: {
      name: 'API Support',
      url: 'https://www.example.com/support',
      email: config.get('contact.app_admin'),
    },
    license: {
      name: 'MIT',
      url: 'https://opensource.org/licenses/MIT',
    },
  },
  host: `${config.get('express.host')}:${config.get('express.port')}`,
  // basePath: '/api',
  schemes: ['http'],
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    // BearerAuth: {
    //   type: 'apiKey',
    //   name: 'Authorization',
    //   in: 'header',
    //   description: 'JWT bearer token',
    // },
    basicAuth: {
      type: 'basic',
      description: 'HTTP Basic Authentication',
    },
  },
  security: [
    {
      basicAuth: [],
    },
  ],
  tags: [
    {
      name: 'cohorts',
      description: 'Operations related to cohorts',
    },
    {
      name: 'general',
      description: 'General operations',
    },
  ],
  responses: {
    UnauthorizedError: {
      description: 'Authentication information is missing or invalid',
    },
    ForbiddenError: {
      description: 'Access denied',
    },
    NotFoundError: {
      description: 'Resource not found',
    },
    InternalServerError: {
      description: 'Internal server error',
    },
  },
  definitions: {
    Cohort: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          format: 'uuid',
          description: 'The cohort ID',
          example: '123e4567-e89b-12d3-a456-426614174000',
        },
        name: {
          type: 'string',
          description: 'The cohort name',
          example: 'Cohort 1',
        },
        query: {
          type: 'object',
          description: 'The cohort query',
          example: {},
        },
        created_at: {
          type: 'string',
          format: 'date-time',
          description: 'The cohort creation date',
          example: '2021-01-01T00:00:00Z',
        },
        description: {
          type: 'string',
          description: 'The cohort description',
          example: 'This is a cohort description',
        },
        metadata: {
          type: 'object',
          description: 'The cohort metadata',
          example: {},
        },
        updated_at: {
          type: 'string',
          format: 'date-time',
          description: 'The cohort update date',
          example: '2021-01-01T00:00:00Z',
        },
        author_username: {
          type: 'string',
          description: 'The cohort author username',
          example: 'user1',
        },
        is_locked: {
          type: 'boolean',
          description: 'Indicates if the cohort is locked',
          example: false,
        },
        is_protected: {
          type: 'boolean',
          description: 'Indicates if the cohort is protected',
          example: false,
        },
        is_published: {
          type: 'boolean',
          description: 'Indicates if the cohort is published',
          example: false,
        },
        size: {
          type: 'integer',
          description: 'The cohort size',
          example: 0,
        },
        author_id: {
          type: 'string',
          format: 'int',
          description: 'The author ID',
          example: 1,
        },
        author_name: {
          type: 'string',
          description: 'The author name',
          example: 'User 1',
        },
        author_email: {
          type: 'string',
          description: 'The author email',
          example: 'user1@example.com',
        },
      },
    },
  },
};

const outputFile = '../../swagger_output.json';
const endpointsFiles = ['../routes/index.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);
