const swaggerAutogen = require('swagger-autogen')({ openapi: '3.0.0' });
const config = require('config');
const cohortModel = require('../services/cohorts/model');

const doc = {
  info: {
    title: 'API',
    description: 'Auto generated by the <b>swagger-autogen</b> module.',
    version: '1.0.0',
    license: {
      name: 'MIT',
      url: 'https://opensource.org/licenses/MIT',
    },
    contact: {
      name: 'API Support',
      url: 'https://www.example.com/support',
      email: config.get('contact.app_admin'),
    },
  },
  servers: [
    {
      url: `http://${config.get('express.host')}:${config.get('express.port')}`,
    },
  ],
  security: [
    {
      basicAuth: [],
    },
  ],
  tags: [
    {
      name: 'cohorts',
      description: 'Operations related to cohorts',
    },
    {
      name: 'general',
      description: 'General operations',
    },
  ],
  components: {
    securitySchemes: {
      basicAuth: {
        type: 'http',
        scheme: 'basic',
        description: 'HTTP Basic Authentication',
      },
    },
    requestBodies: {
      Cohort: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                query: {
                  $ref: '#/components/schemas/CohortQuery',
                },
                is_published: { type: 'boolean', default: false },
                is_locked: { type: 'boolean', default: false },
                is_protected: { type: 'boolean', default: false },
                description: { type: 'string' },
                metadata: { type: 'object' },
              },
              required: ['name', 'query'],
            },
          },
        },
      },
    },
    '@schemas': {
      BadRequestError: {
        type: 'object',
        properties: {
          errors: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                type: {
                  type: 'string',
                  description: 'The error type',
                },
                msg: {
                  type: 'string',
                  description: 'The error message',
                },
                path: {
                  type: 'string',
                  description: 'The path to field with error',
                },
                location: {
                  type: 'string',
                  description: 'The location of the field with error',
                },
              },
            },
          },
        },
        example: {
          errors: [{
            type: 'field', msg: 'Invalid query', path: 'query', location: 'body',
          }],
        },
      },
      Error: {
        type: 'object',
        properties: {
          message: {
            type: 'string',
            description: 'The error message',
            example: 'Resource not found',
          },
        },
        example: {
          message: 'Resource not found',
        },
      },
      Cohort: {
        type: 'object',
        properties: {
          id: {
            type: 'string',
            format: 'uuid',
            description: 'The cohort ID',
          },
          name: {
            type: 'string',
            description: 'The cohort name',
          },
          query: {
            $ref: '#/components/schemas/CohortQuery',
          },
          created_at: {
            type: 'string',
            format: 'date-time',
            description: 'The cohort creation date',
          },
          description: {
            type: 'string',
            description: 'The cohort description',
          },
          metadata: {
            type: 'object',
            description: 'The cohort metadata',
          },
          updated_at: {
            type: 'string',
            format: 'date-time',
            description: 'The cohort update date',
          },
          author_username: {
            type: 'string',
            description: 'The cohort author username',
          },
          is_locked: {
            type: 'boolean',
            description: 'Indicates if the cohort is locked',
          },
          is_protected: {
            type: 'boolean',
            description: 'Indicates if the cohort is protected',
          },
          is_published: {
            type: 'boolean',
            description: 'Indicates if the cohort is published',
          },
          size: {
            type: 'integer',
            description: 'The cohort size',
          },
          author_id: {
            type: 'string',
            format: 'int',
            description: 'The author ID',
          },
          author_name: {
            type: 'string',
            description: 'The author name',
          },
          author_email: {
            type: 'string',
            description: 'The author email',
          },
        },
      },
      CohortQuery: cohortModel.querySchema,
    },
  },
};

const outputFile = '../../swagger_output.json';
const endpointsFiles = ['../routes/index.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);
