const swaggerAutogen = require('swagger-autogen')();
const config = require('config');

const doc = {
  info: {
    title: 'API',
    description: 'Auto generated by the <b>swagger-autogen</b> module.',
    contact: {
      name: 'API Support',
      url: 'https://www.example.com/support',
      email: config.get('contact.app_admin'),
    },
    license: {
      name: 'MIT',
      url: 'https://opensource.org/licenses/MIT',
    },
  },
  host: `${config.get('express.host')}:${config.get('express.port')}`,
  // basePath: '/api',
  schemes: ['http'],
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    // BearerAuth: {
    //   type: 'apiKey',
    //   name: 'Authorization',
    //   in: 'header',
    //   description: 'JWT bearer token',
    // },
    basicAuth: {
      type: 'basic',
      description: 'HTTP Basic Authentication',
      scopes: {
        'read:cohorts': 'Grants read access to cohorts',
        'write:cohorts': 'Grants write access to cohorts',
      },
    },
  },
  security: [
    {
      basicAuth: [],
    },
  ],
  tags: [
    {
      name: 'cohorts',
      description: 'Operations related to cohorts',
    },
    {
      name: 'general',
      description: 'General operations',
    },
  ],
  // responses: {
  //   UnauthorizedError: {
  //     description: 'Authentication information is missing or invalid',
  //   },
  //   ForbiddenError: {
  //     description: 'Access denied',
  //   },
  //   NotFoundError: {
  //     description: 'Resource not found',
  //     schema: {
  //       $ref: '#/definitions/Error',
  //     },
  //   },
  //   InternalServerError: {
  //     description: 'Internal server error',
  //   },
  // },
  definitions: {
    BadRequestError: {
      type: 'object',
      properties: {
        errors: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              type: {
                type: 'string',
                description: 'The error type',
              },
              msg: {
                type: 'string',
                description: 'The error message',
              },
              path: {
                type: 'string',
                description: 'The path to field with error',
              },
              location: {
                type: 'string',
                description: 'The location of the field with error',
              },
            },
          },
        },
      },
      example: {
        errors: [{
          type: 'field', msg: 'Invalid query', path: 'query', location: 'body',
        }],
      },
    },
    Error: {
      type: 'object',
      properties: {
        message: {
          type: 'string',
          description: 'The error message',
          example: 'Resource not found',
        },
      },
      example: {
        message: 'Resource not found',
      },
    },
    Cohort: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          format: 'uuid',
          description: 'The cohort ID',
          example: '123e4567-e89b-12d3-a456-426614174000',
        },
        name: {
          type: 'string',
          description: 'The cohort name',
          example: 'Cohort 1',
        },
        query: {
          type: 'object',
          description: 'The cohort query',
          example: {},
        },
        created_at: {
          type: 'string',
          format: 'date-time',
          description: 'The cohort creation date',
          example: '2021-01-01T00:00:00Z',
        },
        description: {
          type: 'string',
          description: 'The cohort description',
          example: 'This is a cohort description',
        },
        metadata: {
          type: 'object',
          description: 'The cohort metadata',
          example: {},
        },
        updated_at: {
          type: 'string',
          format: 'date-time',
          description: 'The cohort update date',
          example: '2021-01-01T00:00:00Z',
        },
        author_username: {
          type: 'string',
          description: 'The cohort author username',
          example: 'user1',
        },
        is_locked: {
          type: 'boolean',
          description: 'Indicates if the cohort is locked',
          example: false,
        },
        is_protected: {
          type: 'boolean',
          description: 'Indicates if the cohort is protected',
          example: false,
        },
        is_published: {
          type: 'boolean',
          description: 'Indicates if the cohort is published',
          example: false,
        },
        size: {
          type: 'integer',
          description: 'The cohort size',
          example: 0,
        },
        author_id: {
          type: 'string',
          format: 'int',
          description: 'The author ID',
          example: 1,
        },
        author_name: {
          type: 'string',
          description: 'The author name',
          example: 'User 1',
        },
        author_email: {
          type: 'string',
          description: 'The author email',
          example: 'user1@example.com',
        },
      },
      example: {
        id: '123e4567-e89b-12d3-a456-426614174000',
        name: 'Cohort 1',
        query: {},
        created_at: '2021-01-01T00:00:00Z',
        description: 'This is a cohort description',
        metadata: {},
        updated_at: '2021-01-01T00:00:00Z',
        author_username: 'user1',
        is_locked: false,
        is_protected: false,
        is_published: false,
        size: 0,
        author_id: 1,
        author_name: 'User 1',
        author_email: 'user1@example.com',
      },
    },
  },
};

const outputFile = '../../swagger_output.json';
const endpointsFiles = ['../routes/index.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);
