/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/Edit': RouteRecordInfo<'/about/Edit', '/about/Edit', Record<never, never>, Record<never, never>>,
    '/about/Preview': RouteRecordInfo<'/about/Preview', '/about/Preview', Record<never, never>, Record<never, never>>,
    '/audit_logs': RouteRecordInfo<'/audit_logs', '/audit_logs', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/cil': RouteRecordInfo<'/auth/cil', '/auth/cil', Record<never, never>, Record<never, never>>,
    '/auth/google': RouteRecordInfo<'/auth/google', '/auth/google', Record<never, never>, Record<never, never>>,
    '/auth/iucas': RouteRecordInfo<'/auth/iucas', '/auth/iucas', Record<never, never>, Record<never, never>>,
    '/auth/logout': RouteRecordInfo<'/auth/logout', '/auth/logout', Record<never, never>, Record<never, never>>,
    '/auth/microsoft': RouteRecordInfo<'/auth/microsoft', '/auth/microsoft', Record<never, never>, Record<never, never>>,
    '/auth/signup': RouteRecordInfo<'/auth/signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/cohort_access_requests/': RouteRecordInfo<'/cohort_access_requests/', '/cohort_access_requests', Record<never, never>, Record<never, never>>,
    '/cohort_access_requests/[id]': RouteRecordInfo<'/cohort_access_requests/[id]', '/cohort_access_requests/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cohorts/': RouteRecordInfo<'/cohorts/', '/cohorts', Record<never, never>, Record<never, never>>,
    '/cohorts/builder': RouteRecordInfo<'/cohorts/builder', '/cohorts/builder', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/data_browser/': RouteRecordInfo<'/data_browser/', '/data_browser', Record<never, never>, Record<never, never>>,
    '/data_browser/[category]': RouteRecordInfo<'/data_browser/[category]', '/data_browser/:category', { category: ParamValue<true> }, { category: ParamValue<false> }>,
    '/dataproducts/': RouteRecordInfo<'/dataproducts/', '/dataproducts', Record<never, never>, Record<never, never>>,
    '/datasets/[datasetId]/': RouteRecordInfo<'/datasets/[datasetId]/', '/datasets/:datasetId', { datasetId: ParamValue<true> }, { datasetId: ParamValue<false> }>,
    '/datasets/[datasetId]/filebrowser': RouteRecordInfo<'/datasets/[datasetId]/filebrowser', '/datasets/:datasetId/filebrowser', { datasetId: ParamValue<true> }, { datasetId: ParamValue<false> }>,
    '/datasets/ingest': RouteRecordInfo<'/datasets/ingest', '/datasets/ingest', Record<never, never>, Record<never, never>>,
    '/datasetUpload/': RouteRecordInfo<'/datasetUpload/', '/datasetUpload', Record<never, never>, Record<never, never>>,
    '/datasetUpload/new': RouteRecordInfo<'/datasetUpload/new', '/datasetUpload/new', Record<never, never>, Record<never, never>>,
    '/hdw/Analysis': RouteRecordInfo<'/hdw/Analysis', '/hdw/Analysis', Record<never, never>, Record<never, never>>,
    '/hdw/cohorts/': RouteRecordInfo<'/hdw/cohorts/', '/hdw/cohorts', Record<never, never>, Record<never, never>>,
    '/hdw/cohorts/new': RouteRecordInfo<'/hdw/cohorts/new', '/hdw/cohorts/new', Record<never, never>, Record<never, never>>,
    '/hdw/dashboard': RouteRecordInfo<'/hdw/dashboard', '/hdw/dashboard', Record<never, never>, Record<never, never>>,
    '/hdw/Interventions': RouteRecordInfo<'/hdw/Interventions', '/hdw/Interventions', Record<never, never>, Record<never, never>>,
    '/hdw/Search': RouteRecordInfo<'/hdw/Search', '/hdw/Search', Record<never, never>, Record<never, never>>,
    '/igv/': RouteRecordInfo<'/igv/', '/igv', Record<never, never>, Record<never, never>>,
    '/keys': RouteRecordInfo<'/keys', '/keys', Record<never, never>, Record<never, never>>,
    '/participants/': RouteRecordInfo<'/participants/', '/participants', Record<never, never>, Record<never, never>>,
    '/participants/[id]': RouteRecordInfo<'/participants/[id]', '/participants/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/[projectId]/': RouteRecordInfo<'/projects/[projectId]/', '/projects/:projectId', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/datasets/[datasetId]/': RouteRecordInfo<'/projects/[projectId]/datasets/[datasetId]/', '/projects/:projectId/datasets/:datasetId', { projectId: ParamValue<true>, datasetId: ParamValue<true> }, { projectId: ParamValue<false>, datasetId: ParamValue<false> }>,
    '/projects/[projectId]/datasets/[datasetId]/filebrowser': RouteRecordInfo<'/projects/[projectId]/datasets/[datasetId]/filebrowser', '/projects/:projectId/datasets/:datasetId/filebrowser', { projectId: ParamValue<true>, datasetId: ParamValue<true> }, { projectId: ParamValue<false>, datasetId: ParamValue<false> }>,
    '/projects/new': RouteRecordInfo<'/projects/new', '/projects/new', Record<never, never>, Record<never, never>>,
    '/protocols/': RouteRecordInfo<'/protocols/', '/protocols', Record<never, never>, Record<never, never>>,
    '/protocols/[id]': RouteRecordInfo<'/protocols/[id]', '/protocols/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/rawdata/': RouteRecordInfo<'/rawdata/', '/rawdata', Record<never, never>, Record<never, never>>,
    '/scopes': RouteRecordInfo<'/scopes', '/scopes', Record<never, never>, Record<never, never>>,
    '/snapshots/': RouteRecordInfo<'/snapshots/', '/snapshots', Record<never, never>, Record<never, never>>,
    '/stats': RouteRecordInfo<'/stats', '/stats', Record<never, never>, Record<never, never>>,
    '/survey/complete': RouteRecordInfo<'/survey/complete', '/survey/complete', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
    '/variantXplorer/': RouteRecordInfo<'/variantXplorer/', '/variantXplorer', Record<never, never>, Record<never, never>>,
    '/workflows/': RouteRecordInfo<'/workflows/', '/workflows', Record<never, never>, Record<never, never>>,
  }
}
