[tool.poetry]
name = "workers"
version = "0.1.0"
description = "Worker processes"
authors = ["Deepak Duggirala <deepakduggi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
celery = "~5.2.7"        # 3.3 has broken the app
python-dotenv = "^1.0.1"
sca-rhythm = "^0.6.15"
requests = "^2.32.3"
urllib3 = "<2"           # because of ssl conflicts
glom = "^23.5.0"
cyvcf2 = "^0.31.00"      # macos has issues: ImportError: dlopen(...): symbol not found in flat namespace '_bcf_float_missing' - Fixed by "poetry remove cyvcf2; pip install --no-binary :all: cyvcf2"
tqdm = "^4.67.1"
pytest = "^8.3.4"
pandas = "^2.2.3"
fire = "^0.7.0"
python-slugify = "^8.0.4"
pyvcf3 = "^1.0.3"
pysam = "^0.22.0"
tzdata = "^2024.2"
# psycopg2 = "^2.9.10"
psycopg2-binary = "^2.9.10"
pika = "^1.3.2"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.3.5"
diagrams = "^0.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
